import { useState, useEffect } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Form from 'react-bootstrap/Form';
import Button from 'react-bootstrap/Button';
import { useDispatch, useSelector } from 'react-redux';
import * as AuthenticationSlice from "../redux/auth.slice"
import axios from 'axios'
import TopCorner  from '../components/modal'

export default function Home() {
  const [name, setName] = useState('')
  const [apiData, setApiData] = useState([])
  const [showModal, setShowModal]  = useState(false)
  const dispatch = useDispatch()
  const token = useSelector(AuthenticationSlice.getName)

  const getAllData = () => {
    axios.get('https://electronic-ecommerce.herokuapp.com/api/v1/product')
      .then((response) => {
        setApiData(response.data.data.product)
      })
      .catch((error) => {
        console.error(error)
      })
  }

  useEffect(() => {
    getAllData()
  }, [])

  const formSubmit = (e) => {
    e.preventDefault();
    dispatch(AuthenticationSlice.setName(name))
  }

  const open = () => {
    setShowModal(true)
  }

  const close = () => {
    setShowModal(false)
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
     <button onClick={open}>CLick me</button>
      {showModal && <TopCorner cross={close}/>}
      <Form onSubmit={formSubmit}>
        <Form.Group className="mb-3" controlId="formBasicEmail">
          <Form.Label>Email address</Form.Label>
          <Form.Control type="text" placeholder="Enter email" onChange={(e) => setName(e.target.value)} />
          <Form.Text className="text-muted">
             never share your email with anyone else.
          </Form.Text>
        </Form.Group>
        <Button variant="primary" type="submit">
          Submit
        </Button>
      </Form>
    </div>
  )
}
