import { useState, useEffect } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Form from 'react-bootstrap/Form';
import Button from 'react-bootstrap/Button';
import { useDispatch, useSelector } from 'react-redux';
import * as AuthenticationSlice from "../redux/auth.slice"
import axios from 'axios'
import Navigationbar from '../components/navbar';
import CardComponent from '../components/card-component/CardComponent';
import {Col, Row} from 'react-bootstrap'

export default function Home() {
  const [name, setName] = useState('')
  const [apiData, setApiData] = useState([])
  const dispatch = useDispatch()
  

  const getAllData = () => {
    axios.get('https://electronic-ecommerce.herokuapp.com/api/v1/product')
      .then((response) => {
        setApiData(response.data.data.product)
      })
      .catch((error) => {
        console.error(error)
      })
  }

  useEffect(() => {
    getAllData()
  },[])



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigationbar />
      <section className={styles.items}>
      <div className="row m-20" >
      {apiData && apiData.map(data =>  <CardComponent key={data.id} item={data}/>)}
      </div>
      </section>

    </div>
  )
}
